apiVersion: v1
kind: Namespace
metadata:
  name: "mynamespace"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
  namespace: mynamespace
spec:
  containers:
  - name: orange
    image: nginx
